server:
  shutdown: graceful
  servlet:
    context-path: /home
spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: @project.artifactId@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
knife4j:
  enable: true
  documents:
    - group: @knife4j.version@
      name: @project.artifactId@
      #        markdown文件路径
      locations: classpath:md/*
  basic:
    enable: true
    username: admin
    password: admin
  setting:
    language: zh-CN
    swaggerModelName: Model Name
  #    新版本升级后无此参数，添加是为了 Value 注入动态参数，所以此处自定义参数
  contact:
    name: Jovi
    url: http://www.dream.com:8001/home
    email: 506997994@qq.com
  info:
    group-name: @project.artifactId@-@project.version@
    base-package: com.dream.home
    title: @project.artifactId@ API Doc
    description: @project.artifactId@ By Jovi
    version: @project.version@
    service-url: http://www.dream.com:8001/home/doc.html
    license: Apache License, Version 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html